# Generated by Django 5.2.1 on 2025-06-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
